services:
  # organiser:
  #   image: "localhost/organiser"
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: "postgres://organiser:supasecret@postgres:5432/organiser"
  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: organiser
      POSTGRES_PASSWORD: supasecret
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
