services:
  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: organiser
      POSTGRES_PASSWORD: supasecret
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  redis:
    image: "redis:alpine"
    ports:
      - "6379"